### ISSUE TITLE
🆕 Provider Suggestion | AzireVPN

### ISSUE THREAD

**Issue by weeeee-alias-21** [privacytoolsIO/privacytools.io#1478] opened 2019-11-10 03:45 UTC
## Basic Information

**Name:** AzireVPN
**Category:** [Virtual Private Networks](https://www.privacytools.io/providers/vpn/)
**URL:** https://www.azirevpn.com/
**Wikipedia**: https://www.wikipedia.org/wiki/AzireVPN
**Service Agreements**: https://www.azirevpn.com/terms-of-service

## Description

**Basic Description**:
AzireVPN is an incredibly easy to use VPN provider supporting both [Wireguard](https://www.wikipedia.org/wiki/WireGuard) and [OpenVPN](https://www.wikipedia.org/wiki/OpenVPN). 

**Why use over other contenders?**:
For the most part, just speed and software support. Services like Mullvad are slow and do not always provide the best guides for certain OSes like GNU/Linux or OpenBSD;
in some cases they even appear to miss information like `openresolv` versus `resolvconf`.

**Comment by djoate** [comment] 2019-11-10 03:55
Duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/1436

**Comment by weeeee-alias-21** [comment] 2019-11-10 04:12
@djoate Huh, it doesn't show up when you search for it:

- https://archive.is/bevtB

______________________________

Either way, the argument is the same, although I did not state "after consult about issues".

**Closed** 2019-11-10 04:14 UTC
Labels: 🆕 software suggestion

**Comment by Mikaela** [comment] 2019-11-10 13:12
It appears to want a full word ( https://web.archive.org/web/20191110130754/https://github.com/privacytoolsIO/privacytools.io/issues?utf8=%E2%9C%93&q=AzireVPN ) and I don't think we would add them without consultation.
