### ISSUE TITLE
Firefox Addons Installions Require privacy.resistFingerprinting To Be Disabled

### ISSUE THREAD

**Issue by furball514** [privacytoolsIO/privacytools.io#370] opened 2017-12-01 10:02 UTC
it is worth mentioning that when `privacy.resistFingerprinting` setting in `about:config`  is enabled firefox's addons page detects the wrong firefox version and prevents installation of addons like _Cookie AutoDelete,Decentraleyes,uMatrix,NoScript Security Suite_. Best to install all the addons before setting this setting to `true`.

**Comment by Shifterovich** [comment] 2017-12-01 15:43
@beardog108 @kewde

**Comment by Atavic** [comment] 2017-12-01 18:41
**firefox bug** with its [workaround](https://github.com/ghacksuserjs/ghacks-user.js/issues/289#issuecomment-347569709)

**Comment by Vincevrp** [comment] 2019-02-28 19:28
Closing unless anyone can confirm that this is still the case. I don't experience this problem.

**Closed by Vincevrp** 2019-02-28 19:28 UTC

**Comment by Mikaela** [comment] 2019-02-28 22:16
I think it was caused by privacy.resistFingerprinting sending user-agent of the latest ESR when webextensions came and when the ESR with webextensions was released it got fixed a long time ago.

**Comment by Mikaela** [comment] 2019-03-26 09:49
Recently this has started hitting me again with [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/). The workaround above doesn't work for me, and searching further I think this can be kept closed as it's Firefox issue.

* [Bug 1394448: Cannot install Addon with privacy.resistFingerprinting==true](https://bugzilla.mozilla.org/show_bug.cgi?id=1394448)

In case anyone ends up here via search engine or something, my workaround is to append [`/versions` to the URL](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/) and download/install the latest version compatible with Firefox ESR, which is currently 2.7.23.
