### ISSUE TITLE
🆕 Software Suggestion | Add Bittorrent client section

### ISSUE THREAD

**Issue by LaVie024** [privacytoolsIO/privacytools.io#1791] opened 2020-03-19 23:13 UTC
Originally asked this on the Discourse before realizing that I should have posted it on this GitHub. I will copy/paste what I stated in the thread:

"I’ve been wondering this for a decent amount of time, so, honestly, I think we should have a section for bittorrent clients because let’s be honest, uTorrent is fishy, Vuze is popular yet not not entirely OSS, and overall there are better options then them. Bittorrent is a useful thing but should also be private, so we should include FOSS bittorrent clients to list. So is including bittorrent clients a good idea?"

**Comment by Mikaela** [comment] 2020-03-21 07:15
Duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/1788 or at least close enough, but you are at correct place, thank you.

**Closed by Mikaela** 2020-03-21 07:15 UTC
Labels: ✨ enhancement
