### ISSUE TITLE
🌐 Website Issue | Utilize the Unlicense

### ISSUE THREAD

**Issue by asddsaz** [privacytoolsIO/privacytools.io#957] opened 2019-05-29 20:54 UTC
**Feature**: Switch to the Unlicense license
**More Info**: https://www.wikipedia.org/wiki/Unlicense#License_terms
I realize, we recently switched from the WTFPL.

I wanted to recommend another license over CC0 which can be fairly long.
The unlicense license, a WTFPL equivalence non-offensive license:
If you don't know what it is, take 30 seconds to read it:

> This is free and unencumbered software released into the public domain.
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or
> distribute this software, either in source code form or as a compiled
> binary, for any purpose, commercial or non-commercial, and by any
> means.
> 
> In jurisdictions that recognize copyright laws, the author or authors
> of this software dedicate any and all copyright interest in the
> software to the public domain. We make this dedication for the benefit
> of the public at large and to the detriment of our heirs and
> successors. We intend this dedication to be an overt act of
> relinquishment in perpetuity of all present and future rights to this
> software under copyright law.
> 
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
> IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
> OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
> ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
> OTHER DEALINGS IN THE SOFTWARE.
> 
> For more information, please refer to <http://unlicense.org/>
>

**Comment by asddsaz** [comment] 2019-05-29 20:58
As I understand it, WTFPL has no restrictions. Therefore, you can easily change the license.

**Comment by Mikaela** [comment] 2019-05-30 16:55
I am going to treat this as a duplicate of #955 as my response https://github.com/privacytoolsIO/privacytools.io/issues/955#issuecomment-497401537 applies here too.

**Closed by Mikaela** 2019-05-30 16:55 UTC
Labels: high priority, 🌐 website issue

**Comment by asddsaz** [comment] 2019-05-31 02:19
@Mikaela You are just quoting others responses.

But, anyway here is my response:

> WTFPL is a shitty license. We should use an actual license like MIT or preferably CC0.

Shitty or just offensive because it says f*ck?

> 
Releasing our work into the public domain seems like the correct path. WTFPL currently grants users an unlimited license to use our work, which is maybe fine, but CC0 actually revokes all copyright wherever possible, and falls back to an unlimited license where that's legally not a possibility. CC0 also includes a warranty disclaimer

Not really a reason to deny the Unlicense just recommends CC0.

**Comment by asddsaz** [comment] 2019-05-31 02:20
@Mikaela That issue is about WTFPL no Unlicense.

It it possible for this issue to be reopened?

**Comment by JonahAragon** [comment] 2019-06-01 17:25
>> WTFPL is a shitty license. We should use an actual license like MIT or preferably CC0.
>
> Shitty or just offensive because it says f*ck?

https://github.com/privacytoolsIO/privacytools.io/issues/955#issuecomment-497873261

@Mikaela also addressed the issues with the Unlicense in the comment she linked as well.

> The Free Software Foundation states that "Both public domain works and the lax license provided by the Unlicense are compatible with the GNU GPL." However, for dedicating software to the public domain it recommends CC0 over the Unlicense, stating that **CC0 "is more thorough and mature than the Unlicense"**.[1]
>
> The Fedora Project **recommends CC0 over the Unlicense** because the former is "a more comprehensive legal text".[10]
>
> **The Unlicense has been criticized**, for instance by the OSI, **for being possibly inconsistent and non-standard**, and for making it difficult for some projects to accept Unlicensed code as third-party contributions; leaving too much room for interpretation; and **possibly being incoherent in some legal systems**.[13][14][15]

- https://en.wikipedia.org/wiki/Unlicense#Reception [emphasis mine]

**Comment by JonahAragon** [comment] 2019-06-01 17:29
In any case, the CC0 is not very long (IMO), is very thorough, and is virtually universally understood within the community. You don't need to be intimately familiar with the license text to understand that work licensed under the CC0 license is in the public domain for all intents and purposes.
