### ISSUE TITLE
📝 Correction | RTC/VoIP/JitsiMeet: warn against Firefox / Suggest Chromium based browsers

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1814] opened 2020-04-03 05:55 UTC
## Description

~~Firefox hasn't implemented WebRTC as well as Chromium, so whenever a Firefox user joins a Jitsi Meet call, everyone's performance drops.~~

Jitsi Meet doesn't currently work well with non-Chromium browsers. (https://github.com/privacytoolsIO/privacytools.io/issues/1814#issuecomment-608385536)

* https://github.com/jitsi/jitsi-meet/issues/4758

## Why I am making the suggestion

I have been adding issues to the Jitsi Meet recommendation as I have became aware of them, interested in it and noticed that their issue tracker at times links to our issue tracker. I guess I feel responsible for lacking information in where I have been touching so heavily.

* https://www.privacytools.io/software/real-time-communication/#voip

## My connection with the software

* Firefox: it's my main browser and I am subscribed to some of their Bugzilla issues (and trying to help their Flatpak testing which I haven't done much lately).
* Chromium: a browser alongside Google Chrome that I have installed, but find painful to use as Sidewise just isn't Tree Style Tabs.
* Jitsi Meet: The video chatting app that I find the least bad while I prefer to use Mumble (missing video though). I have root on an association instance, but I am avoiding touching it.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by lgrahl** [comment] 2020-04-03 09:36
I wonder what this has to do with privacy? Frankly, just generally recommending Chromium over Firefox is, in my eyes, plain wrong. For Jitsi, this may make sense but, again, I wonder what it has to do with privacy.

**Comment by dngray** [comment] 2020-04-03 09:48
Well some people maybe using Jitsi as opposed to less privacy friendly WebRTC systems.

Unfortunately it seems that it's not so great in Firefox. Hopefully Mozilla prioritizes fixing these issues as a lot of people are using Jitsi these days.

**Comment by Mikaela** [comment] 2020-04-03 09:52
We are recommending Jitsi Meet as a more privacy friendly alternative to many tools such as _Skype, Viber or Google Hangouts_ (or Zoom #1803), it's the easiest to use worth mentioning tool and I have no idea if Linphone does VoIP and while we in general recommend Firefox https://github.com/jitsi/jitsi-meet/issues/4758 means that users will have poor performance and that can easily mean users degrading to less privacy friendly solutions as "they just work".

We are already warning about them using Google Analytics (https://github.com/jitsi/jitsi-meet/issues/4590) and that it doesn't work without WebRTC and also link to other instances, so I don't see why to not tell our visitors that there is this flaw with Firefox that we are aware of.

Personally I have observed heated discussions about Zoom (which just works) vs Jitsi Meet vs other propietary solutions for a community that needs ~20 people in a conference and whether propietary is even option and the issue with Firefox explains a lot on why things haven't been working properly.

**Comment by lgrahl** [comment] 2020-04-03 10:05
> Well some people maybe using Jitsi as opposed to less privacy friendly WebRTC systems.

Valid point which I agree with. Much better than the initial statement "Firefox hasn't implemented WebRTC as well as Chromium" which is an immoderate oversimplification of a complicated matter where the blame can't be put on Firefox alone.

**Comment by tuxayo** [comment] 2020-04-03 10:46
> Valid point which I agree with. Much better than the initial statement "Firefox hasn't implemented WebRTC as well as Chromium" which is an oversimplification of a complicated matter where the blame can't be put on Firefox alone.

Does Zoom work well with Firefox?

One of the factor we have to be conscious is that the huge difference of means between Chrome and Firefox. And that the fact that Google has web conferencing apps since years (Google Hangout and Google Meet recently) which means they obviously focuses enough resources to make it work great.
And also they can abuse their power due to market share to do things in the way that is the most convenient for them.
And if they lead the work on a given web standard, they will have the advantage that the final spec will be very close to their own implementation on which they started to work on it much earlier.

**Comment by tuxayo** [comment] 2020-04-03 10:53
> Does Zoom works well with Firefox?

And also, without too much hacks. Because if it's significantly harder to circumvent less complete WebRTC implementation, then maybe Zoom could have done it, but not Jitsi Meet.

I don't actually know. But my message is that we can say that Firefox hasn't implemented WebRTC as well as Chromium. Due to the analysis on https://github.com/jitsi/jitsi-meet/issues/4758 and the issue tracker of Mozilla.

But we need more info to know if Jitsi Meet could do much more for good Firefox support.

Which is why the question has been asked which is the concrete Jitsi Meet issue that would help the most Firefox users. https://github.com/jitsi/jitsi-meet/issues/4758#issuecomment-608240993

**Comment by dngray** [comment] 2020-04-03 11:08
Apparently people at Mozilla are looking into this..

**Comment by lgrahl** [comment] 2020-04-03 11:16
Zoom is a different matter because it [kind of uses WebRTC while completely circumventing the audio/video part of it](https://webrtchacks.com/zoom-avoids-using-webrtc/). And while people are saying that this is an ugly hack, it is also somewhat clever because it is bypassing a huge chunk of complexity due to a ton of legacy VoIP-related stuff dragged around in WebRTC (others may disagree with me). This of course is completely unrelated to Zoom being a privacy nightmare.

To my knowledge, Jitsi is also using proprietary non-standard features of WebRTC that are implemented in Chrome but not in Firefox (e.g. Plan-B SDP). Thus, I'd say it is wrong to claim that "Firefox hasn't implemented WebRTC as well as Chromium" on the basis that Jitsi does not work as well in Firefox as it does in Chrome.

**Comment by Mikaela** [comment] 2020-04-03 11:24
> Thus, I'd say it is wrong to claim that "Firefox hasn't implemented WebRTC as well as Chromium" on the basis that Jitsi does not work as well in Firefox as it does in Chrome. 

I summarized the issue as well to the best of my ability in the original submission being an expert in neither Firefox internals, WebRTC or Jitsi Meet. Would you like to suggest a better summary for me to replace that one with?

**Comment by lgrahl** [comment] 2020-04-03 11:37
Since Jitsi is the only A/V conference tool mentioned, I'd recommend simply saying that Jitsi currently does not work well with non-Chromium-based browsers and that it can impact the quality of the conference call for everyone, referring to https://github.com/jitsi/jitsi-meet/issues/4758.

**Comment by lrq3000** [comment] 2020-04-09 11:03
I am in favor of adding a warning, but please someone else also test whether indeed there is a performance drop with Firefox. Privacy is highly important, we all agree here, but without practicability this is meaningless, particularly during the current coronacrisis period where there is a flood of new users who simply want things to work because they already have so many things in their hands to handle right now (eg, teachers having to manage their classes, they certainly don't want nor have the time to spend debugging the videoconferencing app).

**Comment by tuxayo** [comment] 2020-04-09 19:43
> please someone else also test whether indeed there is a performance drop with Firefox

Having followed the long discussions between users and devs on https://github.com/jitsi/jitsi-meet/issues/4758 i can confirm the above is a pretty solid info.

**Comment by jacobgonzales20** [comment] 2020-04-26 20:25
It’s working fine on Firefox now

**Comment by dngray** [comment] 2020-04-27 03:26
Looks like this issue is fixed in Firefox 76 https://github.com/jitsi/jitsi-meet/issues/4758#issuecomment-616132865

**Closed by dngray** 2020-04-27 03:26 UTC
Labels: feedback wanted, streaming, 👁️ browsers, 📝 correction, 🦊 Firefox

**Comment by tuxayo** [comment] 2020-05-24 13:21
> Looks like this issue is fixed in Firefox 76 jitsi/jitsi-meet#4758 (comment)

Hopefully it should be okay.
Does anyone has recent feedback on doing conferences comparable to past ones that weren't usable with Firefox?

Because it's hard to understands which of the related bugs on Firefox are critical for widespread use of Jitsi Meet with Firefox?:

https://bugzilla.mozilla.org/buglist.cgi?columnlist=bug_type%2Cshort_desc%2Cproduct%2Ccomponent%2Cpriority%2Cassigned_to%2Ccf_status_firefox76%2Ccf_status_firefox77%2Ccf_status_firefox78%2Ccf_status_firefox_esr68%2Cbug_status%2Cresolution%2Cchangeddate&list_id=15209821&query_format=advanced&status_whiteboard=jitsi-meet&status_whiteboard_type=substring&query_based_on=

And does anyone knows if Jitsi Meet have implemented all they needed to for widespread use of Jitsi Meet with Firefox?

**Comment by lgrahl** [comment] 2020-05-26 07:39
@nils-ohlmeier, do you have an overview of the original problem with Jitsi and the current situation in regards to "what's missing" for conferences in general? :slightly_smiling_face:

**Comment by nils-ohlmeier** [comment] 2020-05-26 16:54
@lgrahl all I can say is that we are currently working on turning on support for RTX and transport-cc, two features which Jitsi relies on heavily. My hope is that these two features will improve things considerably between Firefox and Jitsi.
Also the Jitsi folks have reworked their Firefox support on their side, which already appears to help.

**Comment by lgrahl** [comment] 2020-05-27 08:24
@nils-ohlmeier So, you don't see any "critical" issues left that would be an excuse to not support Firefox properly?
