### ISSUE TITLE
✨ Feature Suggestion | Recommended XMPP Provider

### ISSUE THREAD

**Issue by sakura974201** [privacytoolsIO/privacytools.io#1774] opened 2020-03-10 06:20 UTC
## Description
Why not list the recommended XMPP providers?

**Comment by Mikaela** [comment] 2020-03-10 08:31
Duplicate of #141, however it looks like the link to https://xmpp.org/getting-started/ has gotten removed on the road.

I think it's releated to #1395 and we aren't interested in maintaining our own list as there are others already and ours would be unlikely to provide much additional value for them.

In case you are interested in XMPP providers, multiple email and DNS providers listed on PrivacyTools do have XMPP servers and you may find them also mentioned on our forum.

**Comment by Mikaela** [comment] 2020-03-10 09:09
Actually maybe this could be something for the wiki?

* https://wiki.privacytools.io/view/Main_Page

**Comment by sakura974201** [comment] 2020-03-10 12:25
I did not know the existence of Wiki.
It is no exaggeration to say that existence is hidden.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment] 2020-03-10 12:40
> I did not know the existence of Wiki.
> It is no exaggeration to say that existence is hidden.

Not hidden, but it was mentioned just a couple of times on the forum and some random issues over here.

**Comment by Mikaela** [comment] 2020-03-10 12:53
It's very new and bit of WIP and I am sure it will be getting more easy to find. I guess I can close this issue in favour of it, but please let me know if you create XMPP pages there as I will be interested in contributing if there is anything I have to say in them.

**Comment by sakura974201** [comment] 2020-03-10 12:53
> 
> 
> > I did not know the existence of Wiki.
> > It is no exaggeration to say that existence is hidden.
> 
> Not hidden, but it was mentioned just a couple of times on the forum and some random issues over here.

No link can be found on `www.privacytools.io` .
There is no description in README.md of this repository.
It is hidden.

**Closed by Mikaela** 2020-03-10 12:53 UTC
Labels: XMPP, ✨ enhancement, 📝 correction, 🗨️ instant messaging (im)

**Comment by Mikaela** [comment] 2020-03-10 12:59
The main place I can think of it being mentioned currently is the Code of Conduct at GitHub that links there

* https://github.com/privacytoolsIO/.github/blob/master/CODE_OF_CONDUCT.md

also if you are using Matrix or following there, it has a small mention in the recommended rooms

* https://chat.privacytools.io/ (note to self, wrong link to CoC)

but as I said, I think its existence will become more obvious
