### ISSUE TITLE
🆕 Software Suggestion | Silence (Secure SMS / MMS)

### ISSUE THREAD

**Issue by wuniversales** [privacytoolsIO/privacytools.io#1590] opened 2019-12-15 21:30 UTC
Name: Silence
Category: Secure SMS / MMS
URL: https://silence.im/

I think they should add an encrypted SMS section, or something like that.
This application is very useful for SMS (Eye, this application does not work with internet)

**Comment by Mikaela** [comment] 2019-12-16 09:20
Duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/766 (ghost) + https://github.com/privacytoolsIO/privacytools.io/pull/634 and https://github.com/privacytoolsIO/privacytools.io/issues/1578.

**Closed by Mikaela** 2019-12-16 09:20 UTC
Labels: 🆕 software suggestion
