### ISSUE TITLE
💬 Discussion | Support i2p

### ISSUE THREAD

**Issue by ghbjklhv** [privacytoolsIO/privacytools.io#983] opened 2019-06-11 00:38 UTC
**Feature**: Make privacytools.io and subdomains accessible via i2p
**Isn't this already done?**: Last I checked, http://privacytools.i2p/ was down
**Why?**: i2p focuses strongly on anonymity and undeniably can process the most traffic compared to any other networks because of its P2P structure.

The only popular active i2p privacy site is [TheTinHat](http://secure.thetinhat.i2p/) and it seems to rarely get updates.

**Comment by beardog108** [comment] 2019-06-11 03:38
Duplicate issue, we used to. See #139

**Comment by ghbjklhv** [comment] 2019-06-11 21:16
@beardog108 That post is outdated, it lists darkest mirrors which are no longer active in the main description. The i2p instance in particular is offline.

**Comment by Mikaela** [comment] 2019-06-12 12:09
Duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/139#issuecomment-489431846

**Closed by Mikaela** 2019-06-12 12:09 UTC
Labels: feedback wanted
