### ISSUE TITLE
Update button caption of about:config in Firefox

### ISSUE THREAD

**Issue by igoose1** [privacytoolsIO/privacytools.io#1602] opened 2019-12-20 10:45 UTC
## Description:

I think with an update long time ago button had been changed to "Accept the Risk and Continue" so it'd be better to update that in `_includes/sections/browser-tweaks.html` on line 9.

https://github.com/privacytoolsIO/privacytools.io/blob/34c099ecaba0c4b196b9f2c74b28f04a965ac410/_includes/sections/browser-tweaks.html#L9

## Screenshot:

There is a screenshot to show what I see when visiting about:config.
![image](https://user-images.githubusercontent.com/28492051/71249701-dce9d080-232e-11ea-8e38-d537e771a549.png)

**Comment by Mikaela** [comment] 2019-12-20 17:08
Duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/1532.

**Closed by Mikaela** 2019-12-20 17:08 UTC
Labels: ✨ enhancement
