### ISSUE TITLE
 Microsoft has acquired GitHub

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#478] opened 2018-06-04 07:23 UTC
https://thenextweb.com/dd/2018/06/03/bloomberg-reports-microsoft-has-acquired-github/

In light of this, I would like us to seriously consider self-hosting a Gogs or GitLab instance. We're not eating our own dog food and setting a rather bad example in regards to self-hosting by using GitHub for issues and pull requests.

If it is agreed upon that this is the way to go, I can help to move all of the issues to the new platform, keeping interlinking intact.

This is a duplicate of https://github.com/nylira/prism-break/issues/2011

**Comment by MrAxlee** [comment] 2018-06-04 14:47
Confirmed they have https://blog.github.com/2018-06-04-github-microsoft/

GitLab has an importer to bring your project across https://docs.gitlab.com/ee/user/project/import/github.html

I'd suggest Gitea as a contender to Gogs if moving to selfhosted - https://github.com/go-gitea/gitea

**Comment by Shifterovich** [comment] 2018-06-04 16:23
We may change hosting but let's keep using GitHub for project management. If we decide to change hosting, I think it's best if @privacytoolsIO self-hosts it again, this time with some hooks that automatically update the website when a new commit is pushed.

**Comment by ohmynameisrico** [comment] 2018-06-05 23:04
Not everyone noticed Gitlab infrastructure is behind Microsoft Azure lol
https://twitter.com/gnaggnoyil/status/1003656811172413440

**Comment by angela-d** [comment] 2018-06-05 23:23
Gitlab is also a few steps short of being owned in part by Google.. which is worse?

Google invested $20 mil to [Gitlab's C funding](https://www.kyivpost.com/technology/google-fund-invests-20-million-gitlab-startup-ukrainian-cofounder.html).

Gitlab is also [moving to Google Cloud](https://about.gitlab.com/2018/04/05/gke-gitlab-integration/).

Next step is their [IPO](https://about.gitlab.com/strategy/) where one can assume Google will take a huge chunk of ownership.

The only choices are to have your code on Microsoft -or- Google's stack (if opting for Gitlab over Github), unless you self-host or go to an independent code host like [Not a Bug](https://notabug.org/) or another corp like Bitbucket.

**Comment by ohmynameisrico** [comment] 2018-06-06 00:37
https://www.reddit.com/r/onions/comments/3ykctz/free_git_repository_hosting_accessible_only_over/
http://gitweb2zl5eh7tp3.onion/

**Comment by ohmynameisrico** [comment] 2018-06-06 00:39
and http://haklab4ulibiyeix.onion/users/sign_in

**Comment by MrTimscampi** [comment] 2018-06-06 14:49
You have to consider the potential for new contributors that using the largest platform brings, as well as the work/money needed to migrate and/or host something, compared to the marginal improvement in privacy it's going to bring.

Basically, right now Github already has access to what you do here. The repository is public, your account is, as well. Everything you do on Github while contributing to a public repository is public.  
Github also uses Google Analytics, so chances are Google also knows you're here. And even if you block Google Analytics, Github is public and scraped by Google's bots, so they likely know you're here anyway.

It's ridiculous to leave Github and all the visibility it brings to the project simply because "Microsoft may now see what we do" when Github is already public and everybody can already see what you do.

**Comment by JonahAragon** [comment] 2019-03-31 04:14
> I think it's best if @privacytoolsIO self-hosts it again, this time with some hooks that automatically update the website when a new commit is pushed.

This is now what is happening: https://www.privacytools.io/ is hosted on our own infrastructure.

Do we want to re-discuss self hosting Git, or is everyone here generally still fine with using GitHub for project management?

**Comment by Shifterovich** [comment] 2019-03-31 09:19
Definitely GitHub. Look at what happened to PRISM BREAK after moving to GitLab (which isn't even self-hosted and is still pretty big).

**Comment by Mikaela** [comment] 2019-03-31 09:37
I am fine with GitHub, but if self-hosting was preferred, I have understood that [Gitea](http://gitea.io/) is an option without much pain (while I have heard GitLab being called as difficult to selfhost).

**Comment by JonahAragon** [comment] 2019-03-31 13:40
Difficulty to host isn’t an issue. Out of alternatives I’d say GitLab would probably be the best option to hosting ourselves. 

I think I do agree we should just stick with GitHub for now though. I’m happy we got off CloudFlare and GitHub Pages, but I think GitHub is still a good solution for the actual project organization. That’s where the users are.

**Comment by quantumpacket** [comment] 2019-03-31 18:20
Maybe someone setup a GitLab mirror? I know a few projects on here who mirror their repo(s) on GitLab.

**Comment by JonahAragon** [comment] 2019-03-31 18:26
What benefits would a mirror provide if we kept working on GitHub? It isn't like the concern is *GitHub could delete our repo at any moment*, and even if that were the case, probably every contributor has a local copy of this repo downloaded to their computer. Moving to an alternative is just a matter of pushing to another host.

The only reason I could think of to move to a new provider is if we collectively decided that the benefits of moving to our own self-hosted provider outweighed the cost of losing GitHub Issues and probably a lot of users, and we moved *everything* over. At this present moment I'm not convinced that is the case.

**Comment by quantumpacket** [comment] 2019-03-31 18:34
@JonahAragon I was trying to make a point about your comment:

> I think GitHub is still a good solution for the actual project organization. That’s where the users are.

Then why not in the meantime setup a mirror so you could at least give people the option to star, fork, etc the repo on GitLab to slowly build up a presence/community there?

**Comment by JonahAragon** [comment] 2019-03-31 20:15
> Then why not in the meantime setup a mirror so you could at least give people the option to star, fork, etc the repo on GitLab to slowly build up a presence/community there?

Because then we'd have two segregated communities and linking discussions between them would be unwieldy at best. I think at the moment it's more beneficial to not fragment the community across platforms.

**Comment by BurungHantu1605** [comment] 2019-04-01 00:13
@Shifterovich What happened to PRISM Break in a nutshell after moving to GitLab?

**Comment by Shifterovich** [comment] 2019-04-01 15:15
The repo is very inactive now compared to how active it was on GH. Look at issues, PRs and stars.

**Comment by blacklight447-ptio** [comment] 2019-08-09 20:12
considering this issues discussion has now moved to issue #1062 , im closing this issue.

**Closed by blacklight447-ptio** 2019-08-09 20:12 UTC
