### ISSUE TITLE
Discussion | Add Video Section

### ISSUE THREAD

**Issue by ggg27** [privacytoolsIO/privacytools.io#1029] opened 2019-07-14 05:18 UTC
## Description
**Description**: Add Video Streaming Section
**In relation to**: #671 

## My Opinion
**Who can you back**:
- [Invidious](https://invidio.us/) / [FreeTube](https://github.com/FreeTubeApp/FreeTube)
- [MediaGoblin](https://www.wikipedia.org/wiki/MediaGoblin) [[public instance](https://goblinrefuge.com/)] [[instance list](https://wiki.mediagoblin.org/Live_instances)] 
- [KopyKate](https://github.com/misses-robot/KopyKate-Big) (**Warning: Uncensored**) [[use over TOR](https://zeronet.readthedocs.io/en/latest/faq/#how-to-use-zeronet-with-the-tor-browser)] [[non-free](https://github.com/misses-robot/KopyKate-Big/issues/22)]

**Why not LBRY or PeerTube or....?**:
These all leak your IP, until https://github.com/lbryio/lbry-sdk/issues/1435 , https://github.com/webtorrent/webtorrent/issues/465 , https://github.com/Chocobozzz/PeerTube/issues/1886 , and https://github.com/Chocobozzz/PeerTube/issues/1967 are fixed I wouldn't think of these as privacy respecting.

Not to say I don't use or appreciate these services, they just aren't ready yet. :)

**Proposal**:
Because of the current lack of proper solutions. Perhaps instead of a "Worth Mentioning" why don't we tell users why other [free software](https://www.wikipedia.org/wiki/Free_software) alternatives aren't privacy respecting?

**Comment by Mikaela** [comment] 2019-07-14 08:29
Duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/1029

**Closed by Mikaela** 2019-07-14 08:29 UTC
Labels: 🆕 software suggestion

**Comment by ggg27** [comment] 2019-07-15 02:45
@Mikaela "Make a youtube tab" seems to be for YouTube clients.

I'm personally for pushing users to decentralized alternatives like Media Goblin, although Invidio.us has more of the shows I want to watch.

These 2 issues are different, and not duplicates. 
Therefore, I would like to request this issue to be reopened.

**Comment by Mikaela** [comment] 2019-07-16 20:03
@ggg27 I renamed that issue, I hope you find it more acceptable now.
