### ISSUE TITLE
🆕 Software Suggestion | BCM

### ISSUE THREAD

**Issue by merlinnusr** [privacytoolsIO/privacytools.io#1662] opened 2020-01-24 23:15 UTC
## Basic Information

**BCM:**
**Android chat:**
**https://bcm.social/**

## Description
BCM is a highly secure communication platform. Each message is strictly encrypted, and no third party can decipher the content.

## Why I am making the suggestion
It's an open source decentralized DAPP chat app.  

✔️Chat without Internet:
Offline Chat supports multi-hop ad-hoc network, with Bluetooth/Wi-Fi interconnections, so that in a specific area, the more people are using the app, the bigger coverage.

✔️""Use Anonymously""
Each user generates a random BCM ID. No phone number or email address is required in order to use BCM. This enables you to use BCM completely anonymously.

✔️Fully End-to-End Encrypted
BCM end-to-end encrypts all your communication including messages, voice calls, group chats, files and even personal profile. Only the intended recipient, and nobody else can read your messages.

✔️Secure Data Vault
BCM uses end-to-end encryption to keep your data secure from the moment you share to the moment your file is opened. It also offers security controls that you can set.

## My connection with the software

I'm not connected with this project

**Comment by danarel** [comment] 2020-01-25 06:22
I'd say at the moment, it would at best be a "worth mentioning" link.

It's rated well by Secure Chat Guide: https://securechatguide.org/decentralizedapps.html#bcm

Usually when I see Blockchain mentioned with an app, thats a huge red flag, but they don't store the messages there, which is great news.

**Comment by sell** [comment] 2020-01-25 10:00
The [privacy policy ](https://bcm.social/license/policy.html) isn’t the worse, few things I don’t like but the concept and how the app runs is pretty good. I might use it and test it out, overall I would say it can be used for a “worth mentioning”.

**Comment by Mikaela** [comment] 2020-01-25 11:07
Duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/1641 and https://github.com/privacytoolsIO/privacytools.io/issues/1059.

Issues I previously noticed in https://github.com/privacytoolsIO/privacytools.io/issues/1641#issuecomment-573358373 are not fixed that I can see (I cannot open the hashsum so I am not certain if that is fixed), so I disagree calling it even as a worth mentioning.

**Closed by Mikaela** 2020-01-25 11:07 UTC
Labels: 🆕 software suggestion, 🔎 research required, 🗨️ instant messaging (im)
