### ISSUE TITLE
✨ Feature Suggestion |  add privacy.trackingprotection.fingerprinting.enabled

### ISSUE THREAD

**Issue by hasux3** [privacytoolsIO/privacytools.io#808] opened 2019-04-01 05:55 UTC
hello, for hardening privacy add this about:config

privacy.trackingprotection.fingerprinting.enabled  ;true

**Comment by Mikaela** [comment] 2019-04-01 09:26
Why was this closed, Is it included to `privacy.resistFingerprinting` or `privacy.trackingprotection.enabled`, or did you confuse it as a duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/809 ?

**Comment by hasux3** [comment] 2019-04-01 11:26
what's your problem to close this topic?
it is new about:config rule add to version 66 to protect user against fingerprint.
privacy.trackingprotection.**fingerprinting**.enabled

**Comment by BurungHantu1605** [comment] 2019-04-02 03:35
> or did you confuse it as a duplicate of #809 ?

That's exactly what happened, @Mikaela

**Comment by BurungHantu1605** [comment] 2019-04-02 03:48
thanks, guys.

**Closed by BurungHantu1605** 2019-04-02 03:48 UTC
Labels: ✨ enhancement

**Comment by Atavic** [comment] 2019-04-10 19:51
When tracking protection is enabled, this entry adds another request to mozilla shavar servers:
"base-fingerprinting-track-digest256"

**Comment by beerisgood** [comment] 2019-04-11 04:30
@Atavic that's the reason why ghacks user.js doesn't use this and instead recommend uBlock Origin

**Comment by Thorin-Oakenpants** [comment] 2019-05-10 18:19
actually the reason the ghacks user.js doesn't use this (and in fact recently removed all Tracking Protection (TP) prefs, none of which were active, i.e they were all commented out) is

- The same pref is used for different levels, and thus duplication of prefs to cover all options = messy
- TP lists (and other prefs, not just list ones) are proliferating (e.g crypto, fingerprinting)
- TP is undergoing other changes, and tie-in's to cookie settings etc: the state of which is changing on a weekly basis if you follow what's going on in studies, telemetry, nightly etc = way too much overhead to follow and keep up to date
- TP will get turned on by default soon at appropriate levels when ready: happy to wait and just let Firefox decide when
- Firefox has a giant UI section for TP: users can do it from the UI
- Firefox has other places to let to control TP, e.g from the urlbar info icon, from the hamburger menu
- Firefox is also probably going to display the number of blocked items: a counter = more visibility when it's enabled by default
- Anyone with an inkling of privacy (e.g all the people who visit PTIO) would have an adblocker of some sort, so I don't see this as mission critical

So, excluding the overhead of trying to keep up with it, it's all just a bit pointless: All PTIO needs to do is recommend users go to the UI setting and enable x, y, z: and even then, it'll be on by default very soon
