### ISSUE TITLE
🆕 Software Suggestion | /e/ OS

### ISSUE THREAD

**Issue by marmotte32** [privacytoolsIO/privacytools.io#1393] opened 2019-10-10 20:20 UTC
## Basic Information

**Name:**
/e/ OS
**Category:**
Operating system for Android Smarphones
**URL:**
https://e.foundation
## Description
/e/ (formerly Eelo) is a free and open-source Android-based mobile operating system and associated online services.
The operating system is a fork of LineageOS and Android.
The custom firmware is developed by the /e/ Foundation, which was founded by French entrepreneur Gaël Duval.
/e/ is presented as privacy software that does not contain proprietary Google apps or services, and challenges the public to "find any parts of the system or default applications that are still leaking data to Google."

**Comment by beerisgood** [comment] 2019-10-10 20:52
https://github.com/privacytoolsIO/privacytools.io/issues/864#issuecomment-527438454

**Comment by Mikaela** [comment] 2019-10-10 20:58
Oh, thanks, closing as a duplicate of #864.

**Closed by Mikaela** 2019-10-10 20:58 UTC
Labels: 🆕 software suggestion, 🔎 research required, 🤖 android
