### ISSUE TITLE
Consider change pfsense to opnsense

### ISSUE THREAD

**Issue by bitdegree67** [privacytoolsIO/privacytools.io#506] opened 2018-08-18 12:56 UTC
I saw you suggesting pfsense. but recently pfsense is buyed by company. and another and better fork is here.
https://opnsense.org/

even m0n0wall (pfsense forked) advice opnsense rather than pfsense

**Comment by dnguyen01** [comment] 2018-08-22 14:25
@bitdegree67 who bought them recently? I don't see any news about it. And why do you want to replace PFSense with OPNSense? The only reason is it's a better fork? How? Why? Also PFSense is still open source the last time I check and they're both on the same level.

If anything, you should say, add OPNSense alongside with PFSense. If you want to replace it, you have to have some damning news about them, they went closed-source, or have a really good argument more than "it's better".

**Comment by Hillside502** [comment] 2018-08-22 18:06
A good trawl through the OPNsense website reveals the thoroughbred --- a racing certainty!

**Comment by bitdegree67** [comment] 2018-08-22 18:32
In any case, I have to use the informations I find

**Comment by Mikaela** [comment] 2019-07-06 11:01
Potentially a duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/497 ?

**Closed** 2019-09-05 13:15 UTC
