### ISSUE TITLE
❌ Software Removal | Signal

### ISSUE THREAD

**Issue by iiitomo** [privacytoolsIO/privacytools.io#1591] opened 2019-12-16 16:41 UTC
Dear all,

I am not sure if it is appropriate to recommend Signal on PrivacyTools: https://forum.f-droid.org/t/we-can-include-signal-in-f-droid/7373

**Comment by Mikaela** [comment] 2019-12-16 16:44
Duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/779 (ghost).

**Closed by Mikaela** 2019-12-16 16:44 UTC
Labels: ❌ software removal
