### ISSUE TITLE
🌐 Website Issue | About the format of “Self-contained Networks”

### ISSUE THREAD

**Issue by GrimPixel** [privacytoolsIO/privacytools.io#1426] opened 2019-10-26 17:52 UTC
## Description
This page is the only one with the earlier taste of design:
https://www.privacytools.io/software/networks/
Any plan to change it?

**Comment by Mikaela** [comment] 2019-10-27 20:18
Yes, I think it's just waiting for someone who understands cards.

Closing as a duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/1286.

**Closed by Mikaela** 2019-10-27 20:18 UTC
Labels: high priority, 🌐 website issue
