### ISSUE TITLE
🆕 Software Suggestion | 1984 Hosting

### ISSUE THREAD

**Issue by ManMade-cube42** [privacytoolsIO/privacytools.io#1627] opened 2020-01-02 22:16 UTC
## Basic Information

**Name:** 1984 Hosting
**Category:** [Secure Hosting Provider](https://www.privacytools.io/providers/hosting/)
**URL (en):** https://www.1984hosting.com/
**About Page:** https://www.1984hosting.com/about/

## Description

> The 1984 Hosting Company was established in 2006 by a couple of Free Software and civil rights enthusiasts. We have since grown to become Iceland's biggest web hosting company by far. Our goal is to offer high quality web hosting and VPS services at a competitive price, always respecting and protecting the civil and political rights of our customers. We only use green energy from renewable, sustainable sources and we always choose free software. - [About Page](https://www.1984hosting.com/about/)

**Comment by Mikaela** [comment] 2020-01-02 22:31
Duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/673.

**Closed by Mikaela** 2020-01-02 22:31 UTC
Labels: 🆕 software suggestion
