### ISSUE TITLE
Freedombox - add to Self-Hosted Cloud Server Software section?

### ISSUE THREAD

**Issue by p2635** [privacytoolsIO/privacytools.io#321] opened 2017-08-23 09:49 UTC
Maybe add Freedombox?
http://freedomboxfoundation.org/
http://freedomboxfoundation.org/learn/

I first found out about this from watching one of the videos on DebConf17 which can be viewed here: [FreedomBox, Libre Personal Server](https://debconf17.debconf.org/talks/113/)

**Comment by Atavic** [comment] 2017-08-27 17:04
A mature project. :+1:

**Comment by Atavic** [comment] 2017-08-27 17:05
It's a mature project.

**Comment by hex-m** [comment] 2017-09-26 14:06
imho this needs a new category. Maybe "Homeserver OS". Other contenders for the category would be YUNOhost, Cozy, Sandstorm.io, Cloudron.

**Comment by nitrohorse** [comment] 2019-08-03 18:46
Closing as dupe of https://github.com/privacytoolsIO/privacytools.io/issues/407.

**Closed by nitrohorse** 2019-08-03 18:46 UTC
