### ISSUE TITLE
🌐 Website Issue | matrix homeserver registration disabled

### ISSUE THREAD

**Issue by teoman002** [privacytoolsIO/privacytools.io#1695] opened 2020-02-08 10:59 UTC
## Description
To register on or connect to our homeserver, simply use https://chat.privacytools.io as the homeserver in your Matrix client.

## Error
Matrix client says that registration has been disabled!

**Comment by blacklight447-ptio** [comment] 2020-02-09 13:27
We have gone invite only because of some heavy abuse we were dealing with, so this is expected behavior, but I will give it to you that the error might make it confusing, and we should point it out more obviously.

**Comment by danarel** [comment] 2020-02-12 21:13
I am going to close this since it's not a website issue and the registration is closed because of abuse and not a technical issue.

**Closed by danarel** 2020-02-12 21:13 UTC
Labels: Service issue, [m], approved, 🌐 website issue

**Comment by Mikaela** [comment] 2020-02-12 22:24
Do we have an announcement anywhere that the registration is currently closed or will someone else just open it again or ask elsewhere about it?
