### ISSUE TITLE
🌐 Website Issue | Change “Avoid US & UK services” at ‘Providers’

### ISSUE THREAD

**Issue by GrimPixel** [privacytoolsIO/privacytools.io#1428] opened 2019-10-26 18:23 UTC
## Description
If I read this page, I will reach a conclusion: Russian and Chinese services are better than US & UK's. Is that so?

I think this page emphasizes too much on laws and thus it doesn't apply to countries where the rule of law absents. This should be added.

**Comment by JonahAragon** [comment] 2019-10-29 20:46
> Is that so?

Are there only four countries on Earth?

**Comment by GrimPixel** [comment] 2019-10-29 22:08
That's not funny.

Using Russian and Chinese services belongs to “avoid US & UK services”, but obviously it's not all of it.

**Comment by GrimPixel** [comment] 2019-10-30 08:31
I don't mean it's wrong mentioning US and UK, but it's partial and thus is misleading.

**Comment by dngray** [comment] 2019-11-12 22:25
Closing as duplicate of #1437

**Closed by dngray** 2019-11-12 22:25 UTC
Labels: high priority, 🌐 website issue
