### ISSUE TITLE
🌐 Website Issue | Canada is wrongfully listed as having key disclosure laws

### ISSUE THREAD

**Issue by YuraBrm** [privacytoolsIO/privacytools.io#1628] opened 2020-01-03 18:57 UTC
## Description

https://www.privacytools.io/providers/ lists Canada under the "Key disclosure laws apply" category and links to this [Wikipedia article](https://en.wikipedia.org/wiki/Key_disclosure_law#Canada), which states the opposite:

> In Canada key disclosure is covered under the Canadian Charter of Rights and Freedoms section 11(c) which states "any person charged with an offence has the right not to be compelled to be a witness in proceedings against that person in respect of the offence;" and protects the rights of individuals that are both citizens and non-citizens of Canada as long as they are physically present in Canada.

[The Charter](https://laws-lois.justice.gc.ca/eng/const/page-15.html)
[CCLA - Canadians Have Legal Right Not To Surrender Their Passwords](https://ccla.org/canadians-legal-right-not-surrender-passwords/)

**Comment by Mikaela** [comment] 2020-01-04 11:38
I am closing this as a duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/1167.

**Closed by Mikaela** 2020-01-04 11:38 UTC
Labels: high priority, 🌐 website issue
